// Code generated by mockery v2.43.2. DO NOT EDIT.

package forward

import mock "github.com/stretchr/testify/mock"

// mockOvhClient is an autogenerated mock type for the ovhClient type
type mockOvhClient struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *mockOvhClient) Delete(_a0 string, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *mockOvhClient) Get(_a0 string, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Post provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockOvhClient) Post(_a0 string, _a1 interface{}, _a2 interface{}) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, interface{}) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockOvhClient creates a new instance of mockOvhClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOvhClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOvhClient {
	mock := &mockOvhClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
